inherit_from:
  - rubocop.performance.yml
  - rubocop.rails.yml
  - rubocop.rake.yml
  - rubocop.rspec.yml

inherit_mode:
  merge:
    - Exclude

AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb
    - config/application.rb

Style/HashSyntax:
  Exclude:
    - spec/views/**/*

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - db/**/*

Style/StringLiterals:
  Exclude:
    - db/**/*

Style/FrozenStringLiteralComment:
  Exclude:
    - db/**/*

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

Layout/LineLength:
  Exclude:
    - bin/bundle

Lint/UselessAssignment:
  Exclude:
    - db/seeds.rb

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 30

Style/CombinableLoops:
  Enabled: false
