require:
  - rubocop-rspec

RSpec/FilePath:
  Enabled: false

RSpec/MultipleExpectations:
  Max: 7

RSpec/LetSetup:
  Enabled: false

RSpec/NamedSubject:
  Enabled: false

RSpec/NestedGroups:
  Max: 4

RSpec/MultipleMemoizedHelpers:
  Enabled: false

RSpec/ExampleLength:
  Max: 10

AllCops:
  Exclude:
    - bin/**/*
    - db/schema.rb

Style/HashSyntax:
  Exclude:
    - spec/views/**/*

Style/Documentation:
  Description: 'Document classes and non-namespace modules.'
  Enabled: false

Style/NumericLiterals:
  Exclude:
    - db/**/*

Style/StringLiterals:
  Exclude:
    - db/**/*

Style/FrozenStringLiteralComment:
  Exclude:
    - db/**/*

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Metrics/PerceivedComplexity:
  Max: 10

Layout/LineLength:
  Exclude:
    - bin/bundle

Lint/UselessAssignment:
  Exclude:
    - db/seeds.rb

Metrics/AbcSize:
  Enabled: false

Metrics/BlockLength:
  Max: 30
