version: '3'

services:
  postgresql:
    image: postgres:15.5-alpine3.18
    command: ["postgres", "-c", "port=${BLAH_BLAH_CHAT_DATABASE_PORT}"]
    volumes:
      - postgres_bbc:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "bbc", "-p", "${BLAH_BLAH_CHAT_DATABASE_PORT}", "-d", "blah_blah_chat_production"]
      interval: 5s
    env_file: .env
    environment:
      POSTGRES_USER: bbc
      POSTGRES_PASSWORD: bbc_password
    ports: 
      - "${BLAH_BLAH_CHAT_DATABASE_PORT}:${BLAH_BLAH_CHAT_DATABASE_PORT}"
    networks:
      - postgres

  redis:
    image: redis:7.2.3-alpine3.18
    volumes:
      - redis_bbc:/data
    command: redis-server
    healthcheck:
      test: [ "CMD", "redis-cli", "--raw", "incr", "ping" ]
      interval: 5s
    networks:
      - redis

  app:
    image: blah-blah-chat:1.1
    # image: ghcr.io/rubygitflow/blah_blah_chat:latest
    ports:
      - '3322:3000'
    env_file: .env
    depends_on:
      - postgresql
      - redis
    healthcheck:
      test: ["CMD", "curl", "-i", "-f", "http://localhost:3000/up"]
      interval: 10s
      timeout: 10s
      retries: 3
    networks:
      - postgres
      - redis

volumes:
  postgres_bbc:
  redis_bbc:

networks:
  postgres:
    driver: bridge
  redis:
    driver: bridge
