name: Tests

on:
  workflow_dispatch:
    inputs: {}
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  tests:
    strategy:
      fail-fast: false
      matrix:
        os: ['ubuntu-latest']
        ruby: ['3.2']
    runs-on: ${{ matrix.os }}
    name: Tests with Ruby ${{ matrix.ruby }}

    services:
      postgres:
        image: postgres:15
        env:
          PGUSER: postgres
          PGPASSWORD: postgres
          POSTGRES_HOST_AUTH_METHOD: trust
        ports:
        - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4

      - name: Install DB Dependencies and Check Connections
        run: |
          DEBIAN_FRONTEND="noninteractive" sudo apt-get install -yqq postgresql-client libpq-dev
          env PGPASSWORD=postgres psql -h localhost -p ${{ job.services.postgres.ports[5432] }} -U postgres -l

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true

      - name: Install Ruby Dependencies
        run: |
          gem install bundler
          bundle install

      - name: Build and Create PostgreSQL Database
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          RAILS_ENV: test
        run: |
          bin/rails db:create
          bin/rails db:migrate

      - name: Run Tests
        run: HEADLESS=true bundle exec rake 

      - name: Run Rubocop
        run: rubocop
