name: Publish Docker image
on: [push]
jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build the blah_blah_chat Docker image
        run: |
          docker build . --tag ghcr.io/rubygitflow/blah_blah_chat:latest
          docker run ghcr.io/rubygitflow/blah_blah_chat:latest
          docker push ghcr.io/rubygitflow/blah_blah_chat:latest
